theme = "dracula"

[editor]
true-color = true
# lsp.auto-signature-help = true
# auto-completion = true
smart-tab.enable = false
soft-wrap.enable = false
cursorline = true
trim-trailing-whitespace = true
trim-final-newlines = true
cursor-shape.insert = "bar"

[editor.indent-guides]
character = "╎"
render = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "error"
