theme = "dracula"

[editor]
true-color = true
lsp.auto-signature-help = false
auto-completion = false
smart-tab.enable = false
soft-wrap.enable = false
cursorline = true
trim-trailing-whitespace = true
trim-final-newlines = true
cursor-shape.insert = "bar"

[editor.indent-guides]
character = "╎"
render = true
skip-levels = 1
