# Ruby

[language-server.solargraph]
command = "/Users/aurels/helix-helpers/bin/solargraph"
config.diagnostics=true
config.formatting=false

[language-server.ruby-lsp]
command = "/Users/aurels/helix-helpers/bin/ruby-lsp"
config = { enabledFeatures = ["documentSymbols", "documentHighlights", "foldingRanges",
                              "selectionRanges", "semanticHighlighting", "formatting",
                              "codeActions"] }

[[language]]
name = "ruby"
language-servers=[{ name="solargraph" }, { name="ruby-lsp" }]


# Javascript

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
validate = "on"
run = "onType"

[[language]]
name = "javascript"
language-servers = [{ name="typescript-language-server" }, { name="eslint" }]
auto-format = false

[[language]]
name = "jsx"
language-servers = [{ name="eslint" }]
auto-format = false
